# -*- mode: ruby -*-
# vi: set ft=ruby :

$common = <<SCRIPT
echo '* Add hosts ...'
echo '127.0.0.1       localhost' > /etc/hosts
echo '' >> /etc/hosts
echo 'ff02::1 ip6-allnodes' >> /etc/hosts
echo 'ff02::2 ip6-allrouters' >> /etc/hosts
echo '' >> /etc/hosts
echo '192.168.99.231 node1.k8s.lab node1' >> /etc/hosts
echo '192.168.99.232 node2.k8s.lab node2' >> /etc/hosts
echo '192.168.99.233 node3.k8s.lab node3' >> /etc/hosts

echo '* Make sure the br_netfilter module is loaded ...'
echo br_netfilter > /etc/modules-load.d/k8s.conf
modprobe br_netfilter

echo '* Install and adjust iptables ...'
apt-get update && apt-get -y install iptables
update-alternatives --set iptables /usr/sbin/iptables-legacy

SCRIPT

$swap = <<SCRIPT
echo '* Turn off SWAP ...'
swapoff -a
sed -i '/swap/ s/^/#/' /etc/fstab

SCRIPT

$sysctl = <<SCRIPT
echo '* Adjust system parameters ...'
cat << EOF | tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF

sysctl --system

SCRIPT

$docker = <<SCRIPT
echo '* Install required packages ...'
apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

echo '* Download and install the Docker repository key ...'
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo '* Add the Docker repository ...'
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

echo '* Install the required container runtime packages ...'
apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io

echo '* Add vagrant user to docker group ...'
usermod -aG docker vagrant

SCRIPT

$k8s = <<SCRIPT
echo '* Download and install the Kubernetes repository key ...'
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo '* Add the Kubernetes repository ...'
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

echo '* Install the required Kubernetes packages ...'
apt-get update && apt-get install -y kubelet=1.33.3-1.1 kubeadm=1.33.3-1.1 kubectl=1.33.3-1.1

echo '* Exclude the Kubernetes packages from being updates ...'
apt-mark hold kubelet kubeadm kubectl

echo '* Adjust containerd configuration ...' 
cp /etc/containerd/config.toml /etc/containerd/config.toml.bak
containerd config default | tee /etc/containerd/config.toml > /dev/null
sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
sed -i 's/pause:3.8/pause:3.10/g' /etc/containerd/config.toml
systemctl restart containerd
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "shekeriev/debian-13"
  config.vm.box_version = "13.2.20251118"
  
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1.k8s.lab"
    node1.vm.network "private_network", ip: "192.168.99.231"
    node1.vm.synced_folder "vagrant/", "/vagrant"
    node1.vm.provision "shell", inline: $common
    node1.vm.provision "shell", inline: $sysctl
    node1.vm.provision "shell", inline: $docker
    node1.vm.provision "shell", inline: $k8s
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2.k8s.lab"
    node2.vm.network "private_network", ip: "192.168.99.232"
    node2.vm.synced_folder "vagrant/", "/vagrant"
    node2.vm.provision "shell", inline: $common
    node2.vm.provision "shell", inline: $sysctl
    node2.vm.provision "shell", inline: $swap
    node2.vm.provision "shell", inline: $docker
    node2.vm.provision "shell", inline: $k8s
  end

  config.vm.define "node3" do |node3|
    node3.vm.hostname = "node3.k8s.lab"
    node3.vm.network "private_network", ip: "192.168.99.233"
    node3.vm.synced_folder "vagrant/", "/vagrant"
    node3.vm.provision "shell", inline: $common
    node3.vm.provision "shell", inline: $docker
    node3.vm.provision "shell", inline: $k8s
  end
end
