apiVersion: v1
kind: Service
metadata:
  name: homework-service
spec:
  type: NodePort
  selector:
    app: homework
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080